name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            54.205.41.206 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNT ...
          name: id_rsa
          if_key_exists: replace

      - name: Deploy to Server
        run: |
            cd /home/ubuntu/actions-runner/_work/New-app/
            cp index.html .

      - name: Start HTTP server
        run: |
          python3 -m http.server 8080 --bind 0.0.0.0 --directory $HOME &
          sleep 5  # Wait for the server to start

          

      - name: Test HTML server
        run: |
          curl -s http://localhost:8080

