name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ssh-key
          chmod 600 ~/.ssh/ssh-key
          ssh-keyscan -H 52.87.156.47 >> ~/.ssh/known_hosts

      - name: Deploy GitHub Actions file
        run: |
          echo 'Copying GitHub Actions file to server...'
          scp -i /home/ubuntu/.ssh/ssh-key .github/workflows/index.html ubuntu@52.87.156.47:~/index.html

      - name: Test Deployment
        run: |
          echo 'Testing deployment...'
          curl http://52.87.156.47/index.html

