name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
       export PYTEST_CACHE_DIR=/home/ubuntu
       cd /home/ubuntu/actions-runner/src
       python -m pytest addition.py
       env:
          pythonLocation: /home/ubuntu/actions-runner/_work/_tool/Python/3.9.17/x64
          LD_LIBRARY_PATH: /home/ubuntu/actions-runner/_work/_tool/Python/3.9.17/x64/lib



