name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 44.201.125.159 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          echo 'Copying index.html to server...'
          scp -i ~/.ssh/id_rsa index.html ubuntu@44.201.125.159:~/index.html

      - name: Test Deployment
        run: |
          echo 'Testing deployment...'
          curl http://44.201.125.159/index.html
