name: Deploy to Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H <SERVER_IP> >> ~/.ssh/known_hosts

      - name: Deploy GitHub Actions file
        run: |
          echo 'Copying GitHub Actions file to server...'
          scp -i ~/.ssh/id_rsa .github/workflows/index.html ubuntu@44.201.125.159:~/index.html

      - name: Test Deployment
        run: |
          echo 'Testing deployment...'
          curl http://<SERVER_IP>/index.html
