name: Multi-Server HTML Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_server1:
    runs-on: ubuntu-latest

    env:
      SERVER_ADDRESS: 44.203.87.54
      SERVER_USERNAME: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_1 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SERVER_ADDRESS >> ~/.ssh/known_hosts

      - name: Create index.html
        run: |
          echo '<html>
          <!-- Your HTML content here -->
          </html>' > $HOME/index.html

      - name: Copy index.html using ssh-agent
        run: |
          scp -o StrictHostKeyChecking=no $HOME/index.html $SERVER_USERNAME@$SERVER_ADDRESS:/home/ubuntu

      - name: Start HTTP server
        run: |
          python3 -m http.server 8080 --bind 0.0.0.0 --directory $HOME &
          sleep 200  # Wait for the server to start
          


      - name: Test HTML server
        run: |
          curl -s http://localhost:8080
          
