name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo $SSH_KEY | base64 -d > ssh-key
          chmod 400 ssh-key
          ssh -i ssh-key -o StrictHostKeyChecking=no ubuntu@44.201.125.159 "cd /home/ubuntu/sample-app-deployment-with-github-actions && GIT_SSH_COMMAND='ssh -i /home/ubuntu/.ssh/ssh-key' git pull origin main"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Code Deploy
        run: |
          echo '<!DOCTYPE html>
            <html>
            <head>
            <title>CPU and Memory Usage Monitor</title>
            <script>
            function updateMetrics() {
              // Get CPU and memory usage
              var cpuUsage = performance.now();
              var memoryUsage = (performance.memory.usedJSHeapSize / 1024 / 1024).toFixed(2);
              // Update the display
              document.getElementById("cpuUsage").textContent = cpuUsage.toFixed(2) + " ms";
              document.getElementById("memoryUsage").textContent = memoryUsage + " MB";
            }
            setInterval(updateMetrics, 1000); // Update every second
            </script>
            </head>
            <body>
            <h1>CPU and Memory Usage Monitor</h1>
            <p><strong>CPU Usage:</strong> <span id="cpuUsage">0.00 ms</span></p>
            <p><strong>Memory Usage:</strong> <span id="memoryUsage">0.00 MB</span></p>
            </body>
            </html>' > $HOME/index.html

      - name: Start HTTP server
        run: |
          python3 -m http.server 8080 --bind 0.0.0.0 --directory $HOME &
          sleep 5  # Wait for the server to start

      - name: Test HTML server
        run: |
          curl -s http://localhost:8080
