name: Hello World with HTML

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start HTTP server
      run: |
        echo "Hello, World!" > index.html
        python3 -m http.server 8080 --bind 0.0.0.0 &
        sleep 5  # Wait for the server to start

    - name: Test HTML server
      run: |
        curl -s http://localhost:8080 
