name: HTML Server

on:
  push:
    branches:
      - main

jobs:
  deploy_server:
    runs-on: self-hosted 
    strategy:
      matrix:
        server: ["52.87.156.47"]  # Add more servers as needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          # Set up SSH for the specific server
          # You can use your SSH private key variable here
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ matrix.server }} >> ~/.ssh/known_hosts

      - name: Deploy HTML Server
        run: |
          # Copy index.html to the server using SCP
          scp -i ~/.ssh/id_rsa index.html ubuntu@52.87.156.47:~/index.html


      - name: Test Deployment
        run: |
          # Test the deployed server
          curl http://52.87.156.47:8080/index.html



