name: Deploy HTML App to Servers

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use 'ubuntu-latest' for compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: Copy HTML App to Server
        run: |
          scp -i /root/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r ./home/* ec2-user@3.86.219.251:/home/
          # Add more servers as needed
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock  # Optional, required if you use ssh-agen
